### ISSUE TITLE
Software Bridge

### ISSUE THREAD

**Issue by Dragon0501** [smaragdschlange/ioBroker.nuki#39]
I plan to use a software bridge. Is it possible to get a token from the software bridge?

**Comment by smaragdschlange** [comment]
Hi,
you'll get the token from the Nuki bridge app when you touch the Android
bridge icon.

Regards, Sven

Dragon0501 <notifications@github.com> schrieb am Fr., 10. Juli 2020, 14:51:

**Comment by Dragon0501** [comment]
Thank you very much! Will try it in about an hour.

**Comment by Dragon0501** [comment]
Works! Thank you! 
The other adapter you suggested doesn't work with the software bridge...

**Comment by Dragon0501** [comment]
Gehe Mal bei dem Namen davon aus dass du Deutsch sprichst... 
Ich habe die Bridge installiert und habe sie eingerichtet sie zeigt alle drei Symbole grün. Wenn ich auf das Bridge Symbol klicke muss ich http API aktivieren um die Daten zu sehen die ich in den Adapter eintippen muss. Die Verbindung unterwegs über die nuki app klappt nicht, da ich jedes Mal wenn ich in der App die Bridge einrichten möchte sagt er ich solle auf den Knopf an der Bridge drücken. Also nur für die Hardwarebridge. Wie bekomme ich die Software Bridge so eingerichtet dass sowohl on the go als auch der iobroker funktionieren?

**Comment by smaragdschlange** [comment]
Hi,hm, wenn ich mir das so durchlese, komme ich zu der Vermutung, dass Du die Software Bridge auf Deinem aktuellen Handy installiert hast und versuchst, mit eben diesem Handy remote das Nuki zu bedienen. Liege ich da richtig?Wenn das nämlich so ist, kann es nicht funktionieren. Die Software Bridge wird gewöhnlich auf einem (meist ausrangierten) Handy installiert, das dann immer im 5m-Umkreis beim Nuki verbleibt. Ich verwende selbst produktiv keine Software Bridge, daher weiß ich nicht, ob es bei der Einrichtung in der Nuki-App irgendwelche Besonderheiten gibt. Vielleicht funktioniert es ja nur über die Nuki Web-API?Gruß SvenVon meinem Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [smaragdschlange/ioBroker.nuki] Software Bridge (#39)Von: Dragon0501 An: "smaragdschlange/ioBroker.nuki" Cc: Smaragdschlange ,Comment 

Gehe Mal bei dem Namen davon aus dass du Deutsch sprichst...

Ich habe die Bridge installiert und habe sie eingerichtet sie zeigt alle drei Symbole grün. Wenn ich auf das Bridge Symbol klicke muss ich http API aktivieren um die Daten zu sehen die ich in den Adapter eintippen muss. Die Verbindung unterwegs über die nuki app klappt nicht, da ich jedes Mal wenn ich in der App die Bridge einrichten möchte sagt er ich solle auf den Knopf an der Bridge drücken. Also nur für die Hardwarebridge. Wie bekomme ich die Software Bridge so eingerichtet dass sowohl on the go als auch der iobroker funktionieren?



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/smaragdschlange/ioBroker.nuki/issues/39#issuecomment-657015034",

"url": "https://github.com/smaragdschlange/ioBroker.nuki/issues/39#issuecomment-657015034",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Dragon0501** [comment]
Nein das hast du missverstanden. Die Bridge läuft auf meinem alten Huawei p9 Lite. Die App läuft auf dem mi 9t pro. Problem ist auch gelöst. Die Bridge hatte sich nicht richtig verbunden. Keine Ahnung wo das Problem lag. Habe das Lock neu mit der Bridge verbunden und nun läuft alles vorbildlich! Vielen Dank für die gute Unterstützung! Ich bin aber nun ein zufriedener User deines Adapters und getreu dem Motto:
Never change a running system!
Werde ich bei deinem Adapter bleiben. Er kann das was ich benötige und gut ist! Danke für die tolle Arbeit!
