### ISSUE TITLE
Adapter adaptation to the current API

### ISSUE THREAD

**Issue by simatec** [smaragdschlange/ioBroker.nuki#55]
Can the adapter be adapted to the current API with changes and adjustments for the Nuki 3.0

**Comment by smaragdschlange** [comment]
Hi,
I'll look into it.

**Comment by simatec** [comment]
Thx for your Support 👌

**Comment by smaragdschlange** [comment]
I have just updated the adapter to version 1.6.0 which should support the new devices (Nuki 3.0 and Smart Door). In the current Nuki bridge API I have not seen any additional changes.
Please install this version from GitHub and test. I would appreciate your feedback since I do not own any of the new devices.

**Comment by simatec** [comment]
Can you please open a forum thread to test it.  
There were some questions about the support of Nuki 3.0 in the forum.  

I just started this myself.  I use a Nuki 2.0 myself
