### ISSUE TITLE
Software Bridge fail

### ISSUE THREAD

**Issue by Reventrop** [smaragdschlange/ioBroker.nuki#65]
Log:

host.iobroker | 2022-03-08 20:36:39.178 | error | instance system.adapter.nuki.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
nuki.0 | 2022-03-08 20:36:38.451 | warn | (19537) Terminated (UNCAUGHT_EXCEPTION): Without reason
nuki.0 | 2022-03-08 20:36:38.449 | info | (19537) terminating
nuki.0 | 2022-03-08 20:36:38.447 | info | (19537) cleaned everything up...
nuki.0 | 2022-03-08 20:36:38.434 | error | (19537) Cannot read property 'stateName' of undefined
nuki.0 | 2022-03-08 20:36:38.432 | error | (19537) TypeError: Cannot read property 'stateName' of undefined at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:318:60) at updateAllLockStates (/opt/iobroker/node_mo
nuki.0 | 2022-03-08 20:36:38.429 | error | (19537) uncaught exception: Cannot read property 'stateName' of undefined
nuki.0 | 2022-03-08 20:36:38.420 | info | (19537) Lock list requested: http://192.168.10.246:8080/list?token=xxxxxx

Same URL opened with Webbrowser: [{"nukiId":xxxxx697,"name":"Zuhause"}]

**Comment by smaragdschlange** [comment]
Hi,
I'll look in to it.

Regards
Sven

**Comment by smaragdschlange** [comment]
Hi there,

there seems to be something wrong with your response in the web browser. I've setup a software bridge with a Nuki smart lock:
My URL: 
http://192.168.178.134:8080/list?token=xxxxxx
My response:
[{"nukiId":xxxxxx201,"name":"Server-Raum","lastKnownState":{"state":255,"stateName":"unknown","batteryCritical":false,"timestamp":"2022-03-20T09:17:11+01:00"}}]

The adapter expects the node "lastKnownState" in order to be able to process the response.
What kind of Nuki device is paired to your software bridge? Is the (remote) access working?

I could prevent this error message from appearing, but unless the bridge (or device) is giving back some kind of state, the adapter will not work anyway...

Regards
Sven
