### ISSUE TITLE
Is NUKI Smart Lock Pro 4th Generation being supported?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [smaragdschlange/ioBroker.nuki#74]
Dear Sven,
this new generation works via WLAN and does not need / does not use a bridge.
How do we handle this in the iOBroker please?
Best regards
Michael

**Comment by skyx3** [comment]
This is not new, the V3 also has WLAN (PRO), but this is only a "WLAN light", you still need a bridge with the Nuki V4 to use the API.

**Comment by jolichter** [comment]
btw: the WLAN power consumption of the Pro models is too high for me, so I prefer the Bridge.

**Comment by smaragdschlange** [comment]
Hi there,
as far as I know, the Nuki Smart Lock Pro 4th Gen still needs a bridge for full functionality without WebAPI. Since this adapter does not support the WebAPI, you'll need a bridge if you want to use this adapter.

Regards
Sven

**Comment by jolichter** [comment]
Hi, thanks for your comment. I no longer use the Nuki Bridge because some functions operate solely over the internet and MQTT is not supported. Instead, I now exclusively use my Nuki Smart Lock Pro 3/4 (including the standard model) with [Nuki Hub](https://github.com/technyon/nuki_hub). This reportedly runs smoothly under HA and works flawlessly for me under ioBroker and the MQTT adapter. If I need to access it externally, I do so via VPN.
